### PR TITLE
Cinder: Add role

### PR DESCRIPTION
**Pull request by erick0z**
Add support for OpenStack Cinder to clear-config-manager

### CODE REVIEW

**Comment by albertomurillo** [comment]
- Add a swupd verify task when a file installed by the bundle is not present.
- cinder.conf.j2 has hardcoded keystone ports 5000 and 35357. use their variables instead

**Comment by erick0z** [comment]
Done.

**Comment by albertomurillo** [comment]
When creating the cinder database user, allow access from localhost.

Refer to https://github.com/clearlinux/clear-config-management/blob/master/roles/os-glance/tasks/glance_db_setup.yml

**Comment by erick0z** [comment]
done, thanks

**Pull request merged**
