### PR TITLE
Feature swift role

### PR DESCRIPTION
**Pull request by erick0z**

### CODE REVIEW

**Comment by albertomurillo** [comment]
Can you squash your commits in a single clean commit?

**Comment by albertomurillo** [comment]
Remove ending white spaces in
- examples/openstack/hosts
- roles/os-swift/README.md

**Comment by albertomurillo** [comment]
Start services in tasks files, handlers should be called
only when a configuration file changes to restart a service
via the notify: <handler name> method
    name: ensure storage nodes swift services
    name: ensure controller swift services
    name: start controller swift services
    name: start storage nodes swift services

**Comment by albertomurillo** [comment]
roles/os-swift/tasks/install.yml
Is running swupd verify every time, please add an args: creates: argument
to limit this task to run ONLY when the files are not installed.

**Comment by albertomurillo** [comment]
Update 
b/roles/os-swift/tasks/swift_project_access.yml 
b/roles/os-swift/tasks/swift_service_entities.yml
b/roles/os-swift/templates/proxy-server.conf.j2
to support http or https and custom keystone ports.

**Comment by albertomurillo** [comment]
Remove "verbose = True" variable, it is deprecated in mitaka.

**Comment by albertomurillo** [comment]
Fix handlers:
- start controller swift services
  should be "restart" the state should be "restarted". 
  The issue with started is that the services will NOT 
  be restarted if the service is up already.
- add notify line when config file changes.
  swift_configure_controller.yml is calling notify and flush handlers
  but swift_configure_storage.yml is calling flush handler but there is
  no notify to any handler
- README.md references to two non existing handlers
- restart swift services
- ensure swift services
- If the handler restart services for controller and storage why is it named _controller_ ?

**Comment by albertomurillo** [comment]
Missing "insecure: yes" option after endpoint in
roles/os-swift/tasks/swift_project_access.yml
roles/os-swift/tasks/swift_service_entities.yml
otherwise it wont work with keystone+ssl

**Comment by erick0z** [comment]
Thanks for the feedback! ;)

**Pull request merged**
